// taken from https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#wit-types
// does not compile
package local:demo

world my-world {
  import host: interface {
    log: func(param: string)
  }

  export run: func()
}


// does not compile either
// interface decoding {
//   record test {
//     t1: u32,
//   }

//   record r {
//     a: u32,
//     b: string,
//   }
// }

// default world decoder {
//   export exports: decoding
// }