// without `package` specifier this does not compile
package sth:local

interface decoding {
  record mytest {
    t1: u32,
  }

  type t2 = tuple<u32, u64> 

  union fancyunion {
    u64,
    string,
  }

  my-function: func() -> (a: u32, b: float32)

}

// `default world decoder` does NOT compile
world decoder {
  export decoding
}